/**
 * Students table — the reference screen component.
 *
 * ★ THIS IS THE WORKED EXAMPLE. New screens (hand-written or generated by
 *   Builder.io Fusion) should look like this one:
 *
 *   - Data arrives as typed props. No fetching, no Supabase import, no `async`.
 *   - `showAssignedStaff` toggles the Admin column set vs. the Staff one; the
 *     same component serves both roles. Hiding a column is presentation, NOT
 *     access control — a staff user simply never receives rows they can't see,
 *     because Row Level Security filters them at the database (PRD §7).
 *   - Every list renders an explicit empty state.
 *   - Dates are formatted with an explicit locale + UTC time zone so server and
 *     client markup match and React does not throw a hydration error.
 */

import Link from "next/link";

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  ApplicationStatusBadge,
  DecisionStatusBadge,
} from "@/components/students/status-badge";
import type { StudentWithApplications } from "@/types/db";

const dateFormatter = new Intl.DateTimeFormat("en-GB", {
  day: "2-digit",
  month: "short",
  year: "numeric",
  timeZone: "UTC",
});

function formatDate(value: string) {
  return dateFormatter.format(new Date(value));
}

export interface StudentsTableProps {
  students: StudentWithApplications[];
  /** Admin sees who a student is assigned to; staff already know it's them. */
  showAssignedStaff?: boolean;
  /** Where a row links to — differs per role's route tree. */
  buildHref?: (studentId: string) => string;
  emptyMessage?: string;
}

export function StudentsTable({
  students,
  showAssignedStaff = false,
  buildHref = (studentId) => `/admin/students/${studentId}`,
  emptyMessage = "No students yet.",
}: StudentsTableProps) {
  if (students.length === 0) {
    return (
      <div className="rounded-lg border border-dashed p-10 text-center">
        <p className="text-sm text-muted-foreground">{emptyMessage}</p>
      </div>
    );
  }

  return (
    <div className="overflow-x-auto rounded-lg border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Student</TableHead>
            <TableHead>File opened</TableHead>
            {showAssignedStaff ? <TableHead>Assigned to</TableHead> : null}
            <TableHead>Universities</TableHead>
            <TableHead>Latest activity</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {students.map((student) => {
            const latest = student.applications[0] ?? null;

            return (
              <TableRow key={student.id}>
                <TableCell className="font-medium">
                  <Link
                    href={buildHref(student.id)}
                    className="underline-offset-4 hover:underline"
                  >
                    {student.full_name}
                  </Link>
                </TableCell>
                <TableCell className="text-muted-foreground">
                  {formatDate(student.file_opened_at)}
                </TableCell>
                {showAssignedStaff ? (
                  <TableCell>
                    {student.assigned_staff ? (
                      student.assigned_staff.full_name
                    ) : (
                      <span className="text-muted-foreground">Unassigned</span>
                    )}
                  </TableCell>
                ) : null}
                <TableCell>
                  {student.applications.length === 0 ? (
                    <span className="text-muted-foreground">None yet</span>
                  ) : (
                    <span>
                      {student.applications.length}
                      <span className="text-muted-foreground">
                        {" · "}
                        {student.applications
                          .map((application) => application.university_name)
                          .join(", ")}
                      </span>
                    </span>
                  )}
                </TableCell>
                <TableCell>
                  {latest ? (
                    <div className="flex flex-wrap gap-1.5">
                      <ApplicationStatusBadge status={latest.application_status} />
                      <DecisionStatusBadge status={latest.decision_status} />
                    </div>
                  ) : (
                    <span className="text-muted-foreground">—</span>
                  )}
                </TableCell>
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
    </div>
  );
}
